services:
  - type: web
    name: college-erp-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend-app.vercel.app
      - key: FRONTEND_URL
        value: https://your-frontend-app.vercel.app
      - key: EMAIL_USER
        value: your-email@gmail.com
      - key: EMAIL_PASS
        value: your-app-password
      - key: RAZORPAY_KEY_ID
        value: your_razorpay_key_id
      - key: RAZORPAY_KEY_SECRET
        value: your_razorpay_key_secret

databases:
  - name: mongodb
    plan: free
